# Generated by Django 6.0.5 on 2026-05-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='item_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
