# Generated by Django 6.0.5 on 2026-05-28 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_part_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='core.location'),
        ),
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='core.category'),
        ),
    ]
