# Generated by Django 6.0.5 on 2026-05-28 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_part_location_alter_part_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='minimum_stock',
        ),
        migrations.CreateModel(
            name='PartLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_locations', to='core.location')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_locations', to='core.part')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('part', 'location'), name='unique_part_location')],
            },
        ),
    ]
