# Generated by Django 6.0.5 on 2026-05-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_part_minimum_stock_partlocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partlocation',
            old_name='is_active',
            new_name='is_default',
        ),
    ]
