# Generated by Django 6.0.5 on 2026-05-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_is_active_partlocation_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='location',
        ),
        migrations.AddField(
            model_name='part',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='parts', through='core.PartLocation', to='core.location'),
        ),
    ]
