# Generated by Django 6.0.5 on 2026-05-28 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_part_location_part_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='part_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movement', to='core.partlocation'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movement', to='core.location'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movement', to='core.part'),
        ),
    ]
