# Generated by Django 6.0.5 on 2026-05-28 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_stockmovement_part_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='location',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='part',
        ),
    ]
